AWSTemplateFormatVersion: '2010-09-09'
Description: 'Just My Links - Complete Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name

  NotificationEmail:
    Type: String
    Description: Email address for monitoring alerts

  BearerToken:
    Type: String
    NoEcho: true
    Description: Bearer token for API authentication

  IsFirstRun:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Set to true for first deployment to use public base image

Conditions:
  IsFirstRunCondition: !Equals
    - !Ref IsFirstRun
    - "true"
  IsNotFirstRunCondition: !Not
    - !Equals
      - !Ref IsFirstRun
      - "true"

Resources:

  # ============================================================================
  # SECRETS RESOURCES
  # ============================================================================

  # Bearer Token Secret
  BearerTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Environment}-just-my-links-bearer-token"
      Description: Bearer token for Just My Links API authentication
      SecretString: !Ref BearerToken

  # ============================================================================
  # STORAGE RESOURCES
  # ============================================================================

  # ECR Repository for Lambda Container
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${Environment}-just-my-links-lambda"
      ImageTagMutability: MUTABLE
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Sid: LambdaECRImageRetrievalPolicy
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - ecr:BatchGetImage
              - ecr:GetDownloadUrlForLayer
            Condition:
              StringLike:
                aws:sourceArn: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
          - Sid: AllowAdminAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - ecr:*
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 2 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # S3 Bucket for all application data
  ApplicationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "just-my-links-${Environment}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            Prefix: logs/
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteOldChromaDBVersions
            Status: Enabled
            Prefix: chromadb/
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ============================================================================
  # MONITORING RESOURCES
  # ============================================================================

  # SNS Topic for Alerts
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Environment}-just-my-links-alerts"
      DisplayName: Just My Links Alerts

  # SNS Subscription for Email Alerts
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertsTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  # CloudWatch Alarm for S3 Bucket Size
  S3BucketSizeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-just-my-links-s3-bucket-size"
      AlarmDescription: Alert when S3 application bucket exceeds size threshold
      MetricName: BucketSizeBytes
      Namespace: AWS/S3
      Statistic: Average
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 1073741824  # 1GB in bytes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref ApplicationBucket
        - Name: StorageType
          Value: StandardStorage
      AlarmActions:
        - !Ref AlertsTopic

  # EventBridge Custom Bus
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "${Environment}-just-my-links"

  # ============================================================================
  # COMPUTE RESOURCES
  # ============================================================================

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-just-my-links-lambda-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref BearerTokenSecret
        - PolicyName: EventBridgeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !GetAtt EventBus.Arn
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: 
                  - !Sub "${ApplicationBucket.Arn}/*"
                  - !GetAtt ApplicationBucket.Arn

  # Lambda Function
  IndexDocumentFunction:
    Type: AWS::Lambda::Function
    Condition: IsNotFirstRunCondition
    Properties:
      FunctionName: !Sub "${Environment}-just-my-links-index-document"
      Description: "Just My Links - index submitted documents"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepository}:latest"
      PackageType: Image
      Timeout: 300
      MemorySize: 1024
      ReservedConcurrentExecutions: 1  # Single concurrent execution
      Environment:
        Variables:
          BEARER_TOKEN_SECRET_ARN: !Ref BearerTokenSecret
          EVENT_BUS_NAME: !Sub "${Environment}-just-my-links"
          APPLICATION_BUCKET: !Ref ApplicationBucket
          ENVIRONMENT_NAME: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # API Gateway HTTP API
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Condition: IsNotFirstRunCondition
    Properties:
      Name: !Sub "${Environment}-just-my-links-api"
      Description: Just My Links HTTP API
      ProtocolType: HTTP
      CorsConfiguration:
        AllowCredentials: false
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"
        AllowOrigins:
          - "*"
        MaxAge: 86400

  # HTTP API Integration
  HttpApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Condition: IsNotFirstRunCondition
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IndexDocumentFunction.Arn}/invocations"
      PayloadFormatVersion: "2.0"

  # HTTP API Route
  HttpApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Condition: IsNotFirstRunCondition
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /index-document"
      Target: !Sub "integrations/${HttpApiIntegration}"

  # HTTP API Stage
  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Condition: IsNotFirstRunCondition
    Properties:
      ApiId: !Ref HttpApi
      StageName: !Ref Environment
      AutoDeploy: true

  # Lambda Permission for HTTP API
  HttpApiLambdaPermission:
    Type: AWS::Lambda::Permission
    Condition: IsNotFirstRunCondition
    Properties:
      FunctionName: !Ref IndexDocumentFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*"

Outputs:
  HttpApiUrl:
    Condition: IsNotFirstRunCondition
    Description: HTTP API endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/index-document"
    Export:
      Name: !Sub "${Environment}-just-my-links-api-url"

  ApplicationBucketName:
    Description: S3 Bucket name for application data (ChromaDB and logs)
    Value: !Ref ApplicationBucket
    Export:
      Name: !Sub "${Environment}-just-my-links-application-bucket"

  LambdaFunctionArn:
    Condition: IsNotFirstRunCondition
    Description: Lambda function ARN
    Value: !GetAtt IndexDocumentFunction.Arn

  EcrRepositoryUri:
    Description: ECR Repository URI
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepository}"

  BearerTokenSecretName:
    Description: Name of the bearer token secret in Secrets Manager
    Value: !Ref BearerTokenSecret
    Export:
      Name: !Sub "${Environment}-just-my-links-bearer-token-secret-name"
